version: "3.1"

services:
  front-dev:
    image: node:18.2.0
    container_name: trivia-back-dev
    command: bash -c "npm install && npm run dev"
    # user: "$(id -u):$(id -g)"
    working_dir: /opt/front
    volumes:
      - .:/opt/front
    
    ports:
      - "4000:4000"

